### ISSUE TITLE
Force sanitize database entries

### ISSUE THREAD

**Issue by rollecode** [devgeniem/wp-sanitize-accented-uploads#6]
I have a larger site and for some reason `wp sanitize all` didn't go through as expected, so I have everything right in Media Library, but in articles the images are in the old format, capitalized and with wrong letters - so lots of 404s. Any way to force sanitize all db entries?

**Comment by onnimonni** [comment]
I think currently it should replace post content. Do you store the broken data eg in meta?

**Comment by onnimonni** [comment]
And I wonder if content has relative links and image links are absolute links.

Can you provide example data?

**Comment by rollecode** [comment]
I think it has something to do with upload dir, previous site was built in a traditional way and in the new site we're using the bedrock-way ([dudestack](https://github.com/digitoimistodude/dudestack)), uploads are in `/media` instead of `/wp-content/uploads`. Right now I'm running Broken Links checker to actually see how many links are broken. All of them are in basic post content attachments.

**Comment by onnimonni** [comment]
The algorithm doesn't have really sophisticated logic. It just looks through all uploads and makes sure that those links are all replaced from the content.

for example if it founds file `/wp-content/uploads/ääkkönen.jpg` it will search instances with the full path of the original file and not just the filename in post content and replaces them with sanitized version `/wp-content/uploads/aakkonen.jpg`.

So it doesn't replace files without paths eg: `ääkkönen.jpg` -> `aakkonen.jpg`.

If you had some links into `/wp-content/uploads/` and some links into `/media/` this won't work correctly either.

**Comment by TeemuSuoranta** [comment]
I don't know whether or not it's any better solution but I have approached replacing image sources as follows:
1. Regex all `<img>` tags (that have the same base address as the site)
2. Regex their 'wp-image-123' class and find their ID
3. Find out their size from CSS class 'size-large'
4. Use `wp_get_attachment_image_src` to get the source from the ID and size
5. Replace the src with new one

This is much more complicated way of doing the same thing. Might be a way over-engineering here, though. If you want to check it out, I've done it with https://github.com/aucor/polylang-copy-content and https://github.com/aucor/polylang-translate-existing-media/.

Replacing links to the images is hard because the `<a>` element doesn't have any classes to identify it. The slow but pretty sure way would be to iterate all uploads, get all of their permalinks and search replace them from everywhere (link to attachment). That's a lot of work, though.

On a side note, if people have used ACF or for any other reason embedded images to post_meta, those should be replaced as well. At least in ACF you can make WYSIWYG editors that save the data probably the same way as the content editor. I've made the same search replace there with my solution to be sure.

**Comment by rollecode** [comment]
Thanks @teemusuoranta. I will look into it on Monday. Much appreciated!

**Comment by rollecode** [comment]
I chose the easier way. Noticed that most of the images had IMG, DSC or WEB uppercase, so replaced every occurrence with lowercase equivalents with mysql query, then installed broken link checker plugin and there was only 10-20 images left with either capitalization or ä ö characters, so fixed those few by hand.

**Comment by onnimonni** [comment]
@ronilaukkarinen Thanks for sharing your solution. I'm sure someone else will end up in same situation sooner or later.

**Comment by rollecode** [comment]
I hope it helps someone!

**Note to self:** Next time when upgrading a site, I'll run `wp sanitize all` _before_ migrating to a new uploads path.
